export const MOROCCO_CITIES = [
    'Agadir',
    'Ait Melloul',
    'Al Hoceima',
    'Asilah',
    'Azilal',
    'Azrou',
    'Ben Guerir',
    'Beni Mellal',
    'Berkane',
    'Benslimane',
    'Berrechid',
    'Bouarfa',
    'Boujdour',
    'Bouskoura',
    'Casablanca',
    'Chefchaouen',
    'Dakhla',
    'Demnate',
    'El Hajeb',
    'El Jadida',
    'Errachidia',
    'Essaouira',
    'Fes',
    'Fkih Ben Salah',
    'Fnideq',
    'Guelmim',
    'Guercif',
    'Ifrane',
    'Inezgane',
    'Jerada',
    'Kelaat Sraghna',
    'Kenitra',
    'Khemisset',
    'Khenifra',
    'Khouribga',
    'Ksar El Kebir',
    'Laayoune',
    'Larache',
    'Marrakech',
    'Martil',
    'Mdiq',
    'Meknes',
    'Midelt',
    'Mohammedia',
    'Nador',
    'Nouaceur',
    'Ouarzazate',
    'Ouezzane',
    'Oujda',
    'Rabat',
    'Safi',
    'Sale',
    'Sefrou',
    'Settat',
    'Sidi Bennour',
    'Sidi Ifni',
    'Sidi Kacem',
    'Sidi Slimane',
    'Skhirate',
    'Smara',
    'Souk El Arbaa',
    'Tangier',
    'Taounate',
    'Taourirt',
    'Taroudant',
    'Tata',
    'Taza',
    'Tetouan',
    'Tiflet',
    'Tinghir',
    'Tiznit',
    'Youssoufia',
    'Zagora',
];
